/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasAdmin;

import VentanasVentas.*;
import Clases.CConexion;
import com.mycompany.sistemadegestiondepuerto.InterfazAdministradorSistema;
import com.mycompany.sistemadegestiondepuerto.InterfazLogin;
import com.mycompany.sistemadegestiondepuerto.InterfazLogin;
import com.mycompany.sistemadegestiondepuerto.InterfazLogin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author villa
 */
public class InterfazRegistrosAdmin extends javax.swing.JFrame {
    CConexion con=new CConexion();
    Connection CConexion=con.estableceConexion();
    

    
    /**
     * Creates new form InterfazOperadorEmbarque
     */
    public InterfazRegistrosAdmin() {
        initComponents();        
        mostrardatos();                     
    }
    
    /*private void cambiarVista(JPanel jpanel){
        
    }
    
    private void activarVista(JPanel jpanel){
               
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        comboTipRegistro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtCantCajas = new javax.swing.JTextField();
        txtCantUnid = new javax.swing.JTextField();
        txtIdInventario = new javax.swing.JTextField();
        Panel_Cuadro_inventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabledatos = new javax.swing.JTable();
        MenuInicio = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATÁLOGO DE PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSQUEDA POR:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        txtTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        combotipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "ID", "NOMBRE", "MARCA" }));
        combotipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        combotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        comboTipRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboTipRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Entrada", "Salida" }));
        comboTipRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        comboTipRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipRegistroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de Registro:");

        txtIdProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Producto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtCantCajas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de cajas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtCantCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantCajasActionPerformed(evt);
            }
        });

        txtCantUnid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de unidades", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtCantUnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantUnidActionPerformed(evt);
            }
        });

        txtIdInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID inventario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtIdInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdProducto)
                            .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combotipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboTipRegistro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantCajas)
                            .addComponent(txtCantUnid)
                            .addComponent(txtIdInventario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCantCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCantUnid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        txtTipo.getAccessibleContext().setAccessibleName("Producto ID:");

        Panel_Cuadro_inventario.setBackground(new java.awt.Color(0, 102, 102));
        Panel_Cuadro_inventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Panel_Cuadro_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Cuadro_inventarioMouseClicked(evt);
            }
        });

        jtabledatos.setBackground(new java.awt.Color(204, 255, 255));
        jtabledatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabledatos.setEnabled(false);
        jtabledatos.setFocusable(false);
        jtabledatos.setRowSelectionAllowed(false);
        jtabledatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabledatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabledatos);

        javax.swing.GroupLayout Panel_Cuadro_inventarioLayout = new javax.swing.GroupLayout(Panel_Cuadro_inventario);
        Panel_Cuadro_inventario.setLayout(Panel_Cuadro_inventarioLayout);
        Panel_Cuadro_inventarioLayout.setHorizontalGroup(
            Panel_Cuadro_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Cuadro_inventarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Panel_Cuadro_inventarioLayout.setVerticalGroup(
            Panel_Cuadro_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Cuadro_inventarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Cuadro_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Cuadro_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Panel_Cuadro_inventario.getAccessibleContext().setAccessibleDescription("");

        Inicio.setText("Inicio");

        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        Inicio.add(CerrarSesion);

        MenuInicio.add(Inicio);

        setJMenuBar(MenuInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        InterfazLogin login = new InterfazLogin();
        login.setLocationRelativeTo(null);
        login.setSize(450,490);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void Panel_Cuadro_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Cuadro_inventarioMouseClicked
        btnactualizar.setEnabled(false);
        btnBuscar.setEnabled(true);
        limpiarentradas();
    }//GEN-LAST:event_Panel_Cuadro_inventarioMouseClicked

    private void jtabledatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabledatosMouseClicked
       /* btnregistrar.setEnabled(false);
        btnactualizar.setEnabled(true);
        int fila=this.jtabledatos.getSelectedRow();
        this.combotipo.setSelectedItem(this.jtabledatos.getValueAt(fila, 0).toString());
        this.txtid.setText(this.jtabledatos.getValueAt(fila, 1).toString());
        this.txtDNI.setText(this.jtabledatos.getValueAt(fila, 2).toString());
        this.txtnombre.setText(this.jtabledatos.getValueAt(fila, 3).toString());
        this.txtapellido.setText(this.jtabledatos.getValueAt(fila, 4).toString());
        this.txtcontrasenia.setText(this.jtabledatos.getValueAt(fila, 5).toString());*/
    }//GEN-LAST:event_jtabledatosMouseClicked

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        mostrardatos();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Inventario_id");
        modelo.addColumn("Producot_id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Marca");
        modelo.addColumn("Cajas");
        modelo.addColumn("Unidades");        
        //modelo.addColumn("Descripcion");
        jtabledatos.setModel(modelo);
        int codigo_buscar;
        String consultasql="", nombre_buscar="", marca_buscar="";
        
        if(combotipo.getSelectedItem().toString()=="ID"){
            codigo_buscar = Integer.parseInt(txtTipo.getText());
            consultasql="SELECT i.inventario_id,i.producto_Producto_id, p.Nombre AS Nombre_Producto, p.Marca, i.Cantidad_Caja, i.Cantidad_Unidad FROM inventario i JOIN producto p ON i.producto_Producto_id = p.Producto_id WHERE  p.Producto_id = "+ codigo_buscar+";";
            
        }
        if (combotipo.getSelectedItem().toString()=="NOMBRE") {
            nombre_buscar = txtTipo.getText();
            consultasql = "SELECT i.inventario_id,i.producto_Producto_id, p.Nombre AS Nombre_Producto, p.Marca, i.Cantidad_Caja, i.Cantidad_Unidad FROM inventario i JOIN producto p ON i.producto_Producto_id = p.Producto_id WHERE  p.Nombre = '"+ nombre_buscar+"';"; 
        }
        if(combotipo.getSelectedItem().toString()=="MARCA"){
            marca_buscar = txtTipo.getText();
            consultasql="SELECT i.inventario_id,i.producto_Producto_id, p.Nombre AS Nombre_Producto, p.Marca, i.Cantidad_Caja, i.Cantidad_Unidad FROM inventario i JOIN producto p ON i.producto_Producto_id = p.Producto_id WHERE p.Marca = '"+ marca_buscar+"';";
        }
        String data[]=new String[6];
        Statement st;
        try{
            st=CConexion.createStatement();
            ResultSet rs=st.executeQuery(consultasql);
            while(rs.next()){
                data[0]=rs.getString(1);
                data[1]=rs.getString(2);
                data[2]=rs.getString(3);
                data[3]=rs.getString(4);
                data[4]=rs.getString(5);
                data[5]=rs.getString(6);
                //data[6]=rs.getString(7);
                modelo.addRow(data);
            }
        } catch(SQLException e){
            System.out.println("Error al mostrar Datos "+ e);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void combotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipoActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarentradas() ;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void comboTipRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipRegistroActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        /* int idProducto,cantidadCaja=0, CantidadUnid=0 , idInvetario;
        String estado, fechaRegistro, User, Observaciones, fechvenci, tipoUser, idUser;
        String nombre_buscar="", marca_buscar="";
        
        
        
        idProducto= Integer.parseInt(txtIdProducto.getText());
        estado = comboTipRegistro.getSelectedItem().toString();
        cantidadCaja=Integer.parseInt(txtCantCajas.getText());
        CantidadUnid=Integer.parseInt(txtCantUnid.getText());
        idInvetario = Integer.parseInt(txtIdProducto.getText());
        
       consultasql="INSERT INTO `sistemadegestiondeinventario`.`registro` (`Registro_id`, `Producto_id`, `Estado`, "
                    + "`Cantidad_caja`, `Cantidad_unidad`, `fecha_de_registro`, `Usuario_registro`, `Observaciones`, "
                    + "`fecha_de_vencimiento`, `usuario_TipoDeUsuario`, `producto_Producto_id`, `usuario_idUsuario`, "
                    + "`inventario_inventario_id`, `inventario_producto_Producto_id`) VALUES "
                    + "('10', '"+idProducto+"','" + estado+"', '"+cantidadCaja+"', '"+CantidadUnid+"', '2024-06-24', "
                    + "'111', 'nada2', '2024-10-24', 'Admin', '"+idProducto+"', '111', '"+idInvetario+"', '"+idProducto+"')";*/
        
      /* consultasql= "INSERT INTO `sistemadegestiondeinventario`.`registro` (`Registro_id`, `Producto_id`, `Estado`, `Cantidad_caja`, `Cantidad_unidad`, `fecha_de_registro`, `Usuario_registro`, `Observaciones`, `fecha_de_vencimiento`, `usuario_TipoDeUsuario`, `producto_Producto_id`, `usuario_idUsuario`, `inventario_inventario_id`, `inventario_producto_Producto_id`) VALUES ('12', '1', 'Salida', '5', '5', '2024-06-24', '111', 'nada2', '2024-10-24', 'Admin', '1', '111', '1', '1');";
       
       
       PreparedStatement st;
       
        try{
            st=CConexion.prepareStatement(consultasql);
            st.executeUpdate();
        } catch(SQLException e){
            System.out.println("Error al guardar Datos "+ e);
        }
    */   
      String consultasql = "INSERT INTO `sistemadegestiondeinventario`.`registro` ( `Producto_id`, `Estado`, `Cantidad_caja`, `Cantidad_unidad`, `fecha_de_registro`, `Usuario_registro`, `Observaciones`, `fecha_de_vencimiento`, `usuario_TipoDeUsuario`, `producto_Producto_id`, `usuario_idUsuario`, `inventario_inventario_id`, `inventario_producto_Producto_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (PreparedStatement st = CConexion.prepareStatement(consultasql)) {
        //st.setInt(1, 13);
        st.setInt(1, Integer.parseInt(txtIdProducto.getText()));
        st.setString(2, comboTipRegistro.getSelectedItem().toString());
        st.setInt(3, Integer.parseInt(txtCantCajas.getText()));
        st.setInt(4, Integer.parseInt(txtCantUnid.getText()));
        st.setDate(5, java.sql.Date.valueOf("2024-06-24"));
        st.setInt(6, 111);
        st.setString(7, "nada2");
        st.setDate(8, java.sql.Date.valueOf("2024-10-24"));
        st.setString(9, "Admin");
        st.setInt(10,Integer.parseInt(txtIdProducto.getText()));
        st.setInt(11, 111);
        st.setInt(12, Integer.parseInt(txtIdInventario.getText()));
        st.setInt(13,Integer.parseInt(txtIdProducto.getText()));

        st.executeUpdate();
        JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente");
        mostrardatos();
    } catch (SQLException e) {
        System.err.println("Error al guardar Datos: " + e.getMessage());
    }
      
      
      
       
       
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCantCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantCajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantCajasActionPerformed

    private void txtCantUnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantUnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantUnidActionPerformed

    private void txtIdInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistrosAdmin().setVisible(true);
            }
        });
    }
    
    private void mostrardatos() {
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("ID Inventario");
        modelo.addColumn("ID Producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Marca");
        modelo.addColumn("Cajas");
        modelo.addColumn("Unidades");        
        //modelo.addColumn("Descripcion");
        
        jtabledatos.setModel(modelo);
        //String consultasql="select * FROM inventario";
        String consultasql="SELECT      i.inventario_id, i.producto_Producto_id, p.Nombre AS Nombre_Producto, p.Marca, i.Cantidad_Caja, i.Cantidad_Unidad FROM inventario i JOIN producto p ON i.producto_Producto_id = p.Producto_id;";
        
        String data[]=new String[6];
        
        Statement st;
        try{
            st=CConexion.createStatement();
            ResultSet rs=st.executeQuery(consultasql);
            while(rs.next()){
                data[0]=rs.getString(1);
                data[1]=rs.getString(2);
                data[2]=rs.getString(3);
                data[3]=rs.getString(4);
                data[4]=rs.getString(5);
                data[5]=rs.getString(6);
                //data[6]=rs.getString(7);
                modelo.addRow(data);
            }
        } catch(SQLException e){
            System.out.println("Error al mostrar Datos "+ e);
        }
    }

    void limpiarentradas() {
        combotipo.setSelectedIndex(0);
        txtTipo.setText("");
        txtIdProducto.setText("");
        txtCantCajas.setText("0");
        txtCantUnid.setText("0");
        comboTipRegistro.setSelectedIndex(0);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuBar MenuInicio;
    private javax.swing.JPanel Panel_Cuadro_inventario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JComboBox<String> comboTipRegistro;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabledatos;
    private javax.swing.JTextField txtCantCajas;
    private javax.swing.JTextField txtCantUnid;
    private javax.swing.JTextField txtIdInventario;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
